### PR TITLE
Fix #734: Fire change event onBlur only if number is changed

### LINKED ISSUE #734: Incorrect change event fired on focus
### Current behavior
We discovered this bug testing your component use in PrimeFaces. 
Original Ticket: https://github.com/primefaces/primefaces/issues/8610

### Expected behavior
<Please describe here the expected behavior>

### Steps to reproduce the problem
1. focus val2
2.change the value, focus val1 via shift-tab
3. val2 will send a AJAX request and update @form (thats all correct!)
4. now val1 already has the focus
5. leave focus of val1
6. val1 fires change event because - but the value has not been changed; trigger is autonumeric.js ln 6004.  It is because `3000" != "3000.0"`. It is comparing the Strings and not the numerical values.

**Current Code:**
```js
      if (this.rawValue !== this.rawValueOnFocus) {
        this._triggerEvent(AutoNumeric.events["native"].change, e.target);
      }
```

**Fixed Code:**
```js
      if (Number(this.rawValue) !== Number(this.rawValueOnFocus)) {
        this._triggerEvent(AutoNumeric.events["native"].change, e.target);
      }
```

Submitting a PR.

### PR DESCRIPTION
**Pull request by melloware**
Fix #734: Compare numbers and not strings when firing onChange event

### CODE REVIEW

**Comment by melloware** [comment]
OK found a better fix.  This still compares the full string values but it just trims padded 0's before comparing which is really the use case we are hitting.

File: src/AutoNumeric.js [hunk 1]
```diff
@@ -7413,7 +7413,7 @@ To solve that, you'd need to either set \`decimalPlacesRawValue\` to \`null\`, o
         this.isEditing = false;
 
         // Send a `change` event if the raw value has been changed since the last focus or 'enter' validation
-        if (this.rawValue !== this.rawValueOnFocus) {
+        if (AutoNumericHelper.trimPaddedZerosFromDecimalPlaces(this.rawValue) !== AutoNumericHelper.trimPaddedZerosFromDecimalPlaces(this.rawValueOnFocus)) {
```
Comment (mhombach) [inline src/AutoNumeric.js:7416]: I'm not 100% into the codebase but does the `trimPaddedZerosFromDecimalPlaces` also properly handle thousand-separators, positve/negative-signs, limited-decimal-places etc?

Comment (melloware) [reply src/AutoNumeric.js:7416]:
```js
/**
     * Remove the trailing zeros in the decimal part of a number.
     *
     * @param {string} numericString
     * @returns {*}
     */
    static trimPaddedZerosFromDecimalPlaces(numericString) {
        numericString = String(numericString);
        if (numericString === '') {
            return '';
        }

        const [integerPart, decimalPart] = numericString.split('.');
        if (this.isUndefinedOrNullOrEmpty(decimalPart)) {
            return integerPart;
        }

        const trimmedDecimalPart = decimalPart.replace(/0+$/g, '');

        let result;
        if (trimmedDecimalPart === '') {
            result = integerPart;
        } else {
            result = `${integerPart}.${trimmedDecimalPart}`;
        }

        return result;
    }
```
