### PR TITLE
fix #582 and add two e2e tests to cover it

### LINKED ISSUE #582: Two digits are removed in plugin when user tries to put forbidden character and press "Backspace" button.
We found next issue in plugin.

Repro steps:
1. Put 123 value
2. Press "a" button.
3. Press "Backspace" button.

Actual:
"2" and "3" digits are removed. Field has "1" value.

Expected:
Only "3" digit should be removed. Field should contain "12" value.

### PR DESCRIPTION
**Pull request by kferenc617**
I've added the result of my investigation into the original report (#582). 

Regarding e2e tests: I've created a new utility function getNumericString() that I plan to replace with the same local codes in other tests to make the e2e tests suites more "DRY"

### CODE REVIEW

File: src/AutoNumeric.js [hunk 1]
```diff
@@ -9133,6 +9133,7 @@ To solve that, you'd need to either set \`decimalPlacesRawValue\` to \`null\`, o
 
         this._setValueParts(left, right);
 
+        this.throwInput = true;  // fix #582: this.throwInput can be false (e.g.: by putting an invalid character previously) and we must enable this flag to ensure that input event is sent and double character is not removed, see also _onKeydown
```
Comment (kferenc617) [inline src/AutoNumeric.js:9136]: btw, throwInput is already modified by this function, near the beginning of this function
